// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/skyhawk-screens/HomeToday.tsx": () => import("../components/mockups/skyhawk-screens/HomeToday.tsx"),
  "./components/mockups/skyhawk-screens/ScheduleCalendar.tsx": () => import("../components/mockups/skyhawk-screens/ScheduleCalendar.tsx"),
  "./components/mockups/skyhawk-screens/WalletCredentials.tsx": () => import("../components/mockups/skyhawk-screens/WalletCredentials.tsx")
};
